io_files:
  geometry: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/gm/Tango_Carbon_gm_exp3.0.nc'

profile: 'individual_spectra'

scene_spec:
  sza: [70., 60, 50, 40, 30, 20, 10, 0] 
  saa: [0.,  0., 0., 0., 0., 0., 0., 0] 
  vza: [0.,  0., 0., 0., 0., 0., 0., 0] 
  vaa: [0.,  0., 0., 0., 0., 0., 0., 0] 
