kernel_parameter:               #parameter to configure the 2D blurring of the scene
    type:    '2D Gaussian'      #type pf kernel, current version has only one option  
    fwhm_x:  300                #FWHM in ACT direction
    fwhm_y:  300                #FWHM in flight direction
    size_factor: 2              #the size of the convolution kernel in units of fwhm
        
spec_settings:              #settings for line-by-line spectra
    wave_start: 1585        #nm
    wave_end:   1685        #nm
    dwave:      0.002       #nm
    
xsec_forced: False          #flag to force new cross section calculation

conv_gases: ['co2','ch4','h2o']