kernel_parameter:               #parameter to configure the 2D blurring of the scene
    type:    '2D Gaussian'      #type pf kernel, current version has only one option  
    fwhm_x:  300                #FWHM in ACT direction
    fwhm_y:  300                #FWHM in flight direction
    size_factor: 2              #the size of the convolution kernel in units of fwhm
        
atmosphere:
    nlay: 30                    #number of atmospheric layers
    dzlay: 1000                 #geometrical thickness of the layers [m]
    
std_atm: 'prof.AFGL.US.std'     #AFGL model atmosphere
    
microHH:
    sim: 'Jaenschwalde_simulation1/'
    time_stamp: '0036000'
    lat_lon_src: [51.83472, 14.46277]                   #latitude, longitude coordinates for source in microHH
        
sgm_filename:
    filename_rad_output: 'Tango_Carbon_sgm_radiance'    #output file for rdiometric scene
    filename_atm_output: 'Tango_Carbon_sgm_atmosphere'  #output file for geophysical scene
    gm_input:            'Tango_Carbon_gm'              #gm output file

spec_settings:              #settings for line-by-line spectra
    wave_start: 1585        #nm
    wave_end:   1685        #nm
    dwave:      0.002       #nm

microHH_settings:
    hour:       11          #00-23
    minute:     15          #only in step of 15 min
    
xsec_forced: False          #flag to force new cross section calculation
s2_forced:   False          #flag to force Sentinel 2 calculation
microHH_forced: False       #flag to force microHH data processing