profile: orbit

sensor:
  dwell_time: 0.2124  # seconds, FMC=1
  start_time: 0.0     # minutes wrt orbit epoch
  end_time: 0.33     # minutes wrt orbit epoch

io_files:
  aocs_navigation: aocs_navigation_truth.nc
  ckd: ../common/ckd.nc
  dem: ../common/gebco_ocssw_v2020.nc
  geometry: geometry_aocs_true.nc
  navigation: navigation.nc
