image: raullaasner/tango

definitions:
  steps:
    - step: &step-defaults
        runs-on:
          - self.hosted
          - linux
        size: 8x #  32 GiB

pipelines:
  default:
    - step:
        <<: *step-defaults
        name: Python
        script:
          - . /etc/profile
          - source /venv/bin/activate
          - pip install -e .
          - bash flake8_check.sh
          - mypy teds
          - pytest
    - step:
        <<: *step-defaults
        name: C++
        script:
          - . /etc/profile
          - bash clang_format_check.sh clang-format-18
          - mkdir build
          - cmake -G Ninja -C CI/initial_cache.cmake -B build
          - cmake --build build -j 6
          - cmake --build build --target test
