image: raullaasner/tango

definitions:
  steps:
    - step: &step-defaults
        runs-on:
          - linux.shell

pipelines:
  default:
    - step:
        <<: *step-defaults
        name: Python
        script:
          - . /etc/profile
          - python -m venv venv
          - source venv/bin/activate
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - bash flake8_check.sh
    - step:
        <<: *step-defaults
        name: C++
        script:
          - . /etc/profile
          - bash clang_format_check.sh clang-format-18
          - mkdir build-l1b
          - cmake -G Ninja -C CI/initial_cache.cmake -S teds/l1al1b -B build-l1b
          - cmake --build build-l1b -j 6
          - mkdir build-im
          - cmake -G Ninja -C CI/initial_cache.cmake -S teds/im -B build-im
          - cmake --build build-im -j 6
