image: raullaasner/tango

definitions:
  steps:
    - step: &step-defaults
        runs-on:
          - self.hosted
          - linux
        size: 8x #  32 GiB

pipelines:
  default:
    - step:
        <<: *step-defaults
        name: Python
        script:
          - . /etc/profile
          - python -m venv venv
          - source venv/bin/activate
          - pip install --upgrade pip
          - pip install -r requirements.txt
    - step:
        <<: *step-defaults
        name: C++
        script:
          - . /etc/profile
          - bash clang_format_check.sh clang-format-18
          - mkdir build
          - >
            cmake
            -G Ninja
            -D CMAKE_CXX_COMPILER=g++
            -D CMAKE_C_COMPILER=gcc
            -D CMAKE_CXX_FLAGS="-O3 -march=native -DNDEBUG"
            -D LIBRARIES=netcdf_c++4;netcdf;hdf5_hl;hdf5;z;dl;blas;lapack
            -S .
            -B build
            - cmake --build build -j 6
