[tool.coverage.run]
omit = ["teds/lib/hapi.py"]

[tool.mypy]

disallow_untyped_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "netCDF4",
    "shapely",
    "geopandas",
    "scipy.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "teds.lib.constants",
    "teds.lib.hapi",
    "teds.lib.libGM",
    "teds.lib.libRT",
    "teds.lib.libSURF",
    "teds.lib.paths",
    "teds.lib.data_netcdf.*",
    "teds.lib.libINV",
    "teds.lib.libOrbSim",
    "teds.lib.libAMF",
    "teds.lib.libATM",
    "teds.lib.libDOAS",
    "teds.lib.libMeteo",
    "teds.lib.libNumTools",
    "teds.lib.libRT_no2",
    "teds.lib.libSGM",
    "teds.lib.libWrite",
    "teds.lib.lib_utils",
    "teds.gm.create_gm_yaml_file",
    "teds.gm.gm",
    "teds.sgm.create_sgm_yaml_file",
    "teds.sgm.sgm_no2",
    "teds.sgm.sgm_Carbon_radscene",
    "teds.sgm.sgm_geoscene",
    "teds.im.create_im_configuration_file_nitro",
    "teds.ckd.ckd_generation.ckd_generator_carbon",
    "teds.ckd.ckd_generation.ckd_generator_nitro",
    "teds.ckd.ckd_generation.generator_class",
    "teds.ckd.ckd_generation.nitro_ckds.*",
    "teds.ckd.create_binning_tables",
    "teds.ckd.__init__",
    "teds.l1al1b.create_l1a1b_configuration_file_nitro",
    "teds.l1l2.create_l2_yaml_file",
    "teds.l1l2.sl2",
    "teds.l1l2.l1bl2_no2",
    "teds.l1l2.l1bl2",
    "teds.l2l4.ModuleCFM",
    "teds.l2l4.ModuleDataContainer",
    "teds.l2l4.ModuleLSQ",
    "teds.l2l4.ModuleLevel2",
    "teds.l2l4.ModulePlume",
    "teds.l2l4.ModulePreProcessing",
    "teds.l2l4.ModuleReadMicroHH",
    "teds.l2l4.ModuleRemoveBackground",
    "teds.l2l4.__init__",
    "teds.l2l4.l2l4",
    "teds.pam.pam",
    "teds.siml1b.radiance_offset",
    "teds.siml1b.siml1b",
    "teds.run_E2E",
]
ignore_errors = true
