filename:
    ckd:            'ckd_kernels_int_full'               #IM calibration key data
    gm:             'Tango_Carbon_gm_'                   #geometry data from GM
    sgm:            'Tango_Carbon_sgm_radiance_'         #SGM radiance input
    level0:         'Tango_Carbon_l0_'                   #level 0 input
    level1b:        'Tango_Carbon_l1b_'                  #level 1b output
    binning_table:  'binning_table'                      #Instrument binning table
    pixel_mask:     'level1b_pixel_mask'                 #level 1b pixel mask

settings:
    van_cittert_steps: 4  #van Citter iteration for stray light correction (0=no correction)
    # Whether to use inteprolating stray light kernels
    stray_interpolating: yes
    geolocation:  0       #calculate geolocation (0 no, 1 yes), currently only 0 possible
    van_cittert_steps: 4  #van Citter iteration for stray light correction (0=no correction) 
    geolocation:       0                                  #calculate geolocation (0 no, 1 yes), currently only 0 possible
    sw_dark:           1                                   #switch dark current (1 on, 0 off)
    sw_nonlin:         1                                   #switch non-linearity (1 on, 0 off)
    sw_prnu:           1                                   #switch pixel response non-uniformity (1 on, 0 off)
    sw_rad:            1                                   #switch radiometric calibration (1 on, 0 off)
