filename:
    ckd_input:      'ckd'                                #IM calibration key data
    gm_input:       'Tango_Carbon_gm_'                   #geometry data from GM
    sgm_input:      'Tango_Carbon_sgm_radiance_'         #SGM radiance input
    level0_input:   'Tango_Carbon_l0_'                   #level 0 input
    level1b_output: 'Tango_Carbon_l1b_'                  #level 1b output
    binning_table:  'binning_table'                      #Instrument binning table
    
settings:
    van_cittert_steps: 4  #van Citter iteration for stray light correction (0=no correction)
    # Whether to use inteprolating stray light kernels
    stray_interpolating: yes
    geolocation:  0       #calculate geolocation (0 no, 1 yes), currently only 0 possible
