profile: individual_spectra

sedf:
  enabled: no

isrf:
  enabled: yes
  fwhm: 0.45
  shape: 2.0

spec_lbl_settings:              #settings for line-by-line spectra
    wave_start: 1575            #nm
    wave_end:   1685            #nm
    dwave:      0.002           #nm

xsec_forced: False              #flag to force new cross section calculation

atmosphere:
  n_layers: 30
  layer_thickness: 1000
  surface_pressure: 101300

afgl_gases: [co2, h2o, ch4]

io_files:
  geometry: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/gm/Tango_Carbon_gm_exp3.0.nc'
  sun_reference: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/solar_spectra/hybrid_reference_spectrum_c2021-03-04_with_unc.nc'
  hapi: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/harpi/'
  afgl: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/AFGL/prof.AFGL.US.std'
  atmosphere: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_atmosphere_exp3.0.nc'
  radiance: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_radiance_exp3.0.nc'
  atmosphere_ref: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_atmosphere_ref_exp3.0.nc'
  dump_xsec: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/tmp/Tango_Carbon_xsec_exp3.0.pkl'
