kernel_parameter:               #parameter to configure the 2D blurring of the scene
    type:    '2D Gaussian'      #type pf kernel, current version has only one option  
    fwhm_x:  300                #FWHM in ACT direction
    fwhm_y:  300                #FWHM in flight direction
    size_factor: 2              #the size of the convolution kernel in units of fwhm
        
atmosphere:
    nlay: 30                    #number of atmospheric layers
    dzlay: 1000                 #geometrical thickness of the layers [m]
        
only_afgl: False

lat_lon_src: [51.83472, 14.46277]                   #latitude, longitude coordinates 

meteo:
  dump: "tmp/microHH.pkl"
  path_data: "/media/jochen/SRON_Data/microHH/Jaenschwalde/"
  filesuffix: "src1_20180523_1100"  # sourcename_yyyymmdd_hhmm
  gases: ["co2"]
        
spec_settings:              #settings for line-by-line spectra
    wave_start: 1585        #nm
    wave_end:   1685        #nm
    dwave:      0.002       #nm
    
xsec_forced: False          #flag to force new cross section calculation
s2_forced:   False          #flag to force Sentinel 2 calculation
meteo_forced: False         #flag to force microHH data processing
