profile: individual_spectra

atmosphere:
  n_layers: 30
  layer_thickness: 1000
  surface_pressure: 101300

scale_gas:                  #only relevant for AFGL profiles
    xco2: 410.              #ppm
    xch4: 1800.             #ppb
    xh2o: 10000.            #ppm

io_files:
  geometry: geometry.nc
  afgl: ../common/prof.AFGL.US.std
  atmosphere: sgm_atmosphere.nc
