profile: individual_spectra

atmosphere:
    nlay: 30                    #number of atmospheric layers
    dzlay: 1000                 #geometrical thickness of the layers [m]

scale_gas:                  #only relevant for AFGL profiles
    xco2: 410.              #ppm
    xch4: 1800.             #ppb
    xh2o: 10000.            #ppm

io_files:
    input_gm: geometry.nc
    input_afgl: ../common/prof.AFGL.US.std
    output_geo: sgm_atmosphere.nc
