profile: individual_spectra

sedf:
  enabled: no

isrf:
  enabled: yes

spec_lbl_settings:              #settings for line-by-line spectra
    wave_start: 1575            #nm
    wave_end:   1685            #nm
    dwave:      0.002           #nm

xsec_forced: False              #flag to force new cross section calculation

atmosphere:
  n_layers: 30
  layer_thickness: 1000
  surface_pressure: 101300

afgl_gases: ['co2','ch4','h2o']

binning_act: 1

io_files:
  geometry: geometry.nc
  sun_reference: ../common/solar_spectrum.nc
  hapi: ../common/hapi/
  afgl: ../common/prof.AFGL.US.std
  atmosphere: sgm_atmosphere.nc
  radiance: sgm_radiance.nc
  atmosphere_ref: sgm_atmosphere_ref.nc
  dump_xsec: xsec.pkl
