profile: individual_spectra

convolve_atm_input: False      #True means lbl spatial convolution of the model atmosphere with SEDF
                               #False means spectral convolution with spatial sampling on model grid

spec_lbl_settings:              #settings for line-by-line spectra
    wave_start: 1575            #nm
    wave_end:   1685            #nm
    dwave:      0.002           #nm

xsec_forced: False              #flag to force new cross section calculation

atmosphere:
    nlay: 30                    #number of atmospheric layers
    dzlay: 1000                 #geometrical thickness of the layers [m]
    psurf: 101300               #surface pressure [Pa]

selected_gases: ['co2','ch4','h2o']

binning_act: 1

io_files:
    input_gm: geometry.nc
    input_sun_reference: ../common/solar_spectrum.nc
    input_hapi: ../common/hapi/
    input_afgl: ../common/prof.AFGL.US.std
    input_sgm_geo: sgm_atmosphere.nc
    output_rad: sgm_radiance.nc
    output_geo_ref: sgm_atmosphere_ref.nc
    dump_xsec: xsec.pkl
