sim_with_noise: False

spec_settings:                                     #settings for spectral grid of measurements
    wave_start: 1590.0009375                       #nm
    wave_end:   1675                               #nm
    dwave:      0.1546875                          #nm

#isrf_settings:
#    type:       'generalized_normal'               #type of ISRF, currently only Gaussian or generalized_normal
#    fwhm:       0.45                               #fwhm  [nm]
#    bcoeff:     0.45                               #only for generalized_normal, bcoeff=1/2 means Gaussian

isrf_settings:
  fwhm: 0.45
  shape: 2.0

snr_model:                                         #SNR instrument model a nd b coefficients
    a_snr:      1.54E-12                           #[e- m2 sr s nm/phot.]
    b_snr:      45501                              #[e-]
    seed:       5                                  #seed for measurement noise

binning_act: 1                                     #binning factor of spectra in ACT direction.

io_files:
    input_sgm: sgm_radiance.nc
    input_gm: geometry.nc
    output_l1b: l1b.nc
