filename:
    ckd_input:      'ckd'                                #IM calibration key data
    gm_input:       'Tango_Carbon_gm_'                   #geometry data from GM
    sgm_input:      'Tango_Carbon_sgm_radiance_'         #SGM radiance input
    level1a_input:  'Tango_Carbon_l0_'                   #level 1a input
    binning_table:  'binning_table'                      #Instrument binning table

settings:
    bin_id:          1                                   #across track binning
    co_adding:       3                                   #along track co-addng
    exp_time:        0.066                               #exposure time [sec]
     # Whether to use interpolating stray light kernels
    stray_interpolating: yes

isrf:
    convolution:     1                                   #switch spectral convolution (1=yes), (0=no)
    fwhm:            0.45                                #full width half max [nm]
    
select_images:       False                               #select certain images form the sgm input
first_image:         0
last_image:          1

noise:
    switch:          1                                   # switch noise on (1) or off (0)
    seed:            100                                 #seed for random generator
    
