settings:
    fmc:             5                                   #forward motion compensation
    bin_id:          1                                   #across track binning
    co_adding:       3                                   #along track co-addng
    exp_time:        0.066                               #exposure time [sec]
    stray_interpolating: yes                             #Whether to use interpolating stray light kernels
    sw_dark:         1                                   #switch dark current (1 on, 0 off)
    sw_nonlin:       1                                   #switch non-linearity (1 on, 0 off)
    sw_prnu:         1                                   #switch pixel response non-uniformity (1 on, 0 off)
    sw_stray:        0                                   #switch dark spectrometer stray light (1 on, 0 off)
    sw_rad:          1                                   #switch radiometric calibration (1 on, 0 off)

isrf:
    convolution:     1                                   #switch spectral convolution (1=yes), (0=no)
    fwhm:            0.45                                #full width half max [nm]
    
select_images:       False                               #select certain images form the sgm input
first_image:         0
last_image:          1

noise:
    switch:          0                                   # switch noise on (1) or off (0)
    seed:            100                                 #seed for random generator
    
