filename:
    ckd_input:      'ckd'                                #IM calibration key data
    gm_input:       'Tango_Carbon_gm_'                   #geometry data from GM
    sgm_input:      'Tango_Carbon_sgm_radiance_'         #SGM radiance input
    level0_input:   'Tango_Carbon_l0_'                   #level 0 input
    binning_table:  'binning_table'                      #Instrument binning table