# gm and sgm profile 
profile:   individual_spectra  # must be the same for gm and sgm
# file names and paths 
# gm output file 
output:    /home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/gm/Tango_Carbon_gm_exp2.0.nc

# setup up geometry and albedo of the scene 
  sza:               [70.0]  # solar zenith angle [degeee] 
  saa:               [70.0]  # solar azimuth angle [degeee] 
  vza:               [0.0]  # viewing zenith angle [degeee] 
  vaa:               [0.0]  # viewing azimuth angle [degeee] 
  sza:               [70.0]  # solar zenith angle [degeee] 
  saa:               [70.0]  # solar azimuth angle [degeee] 
