# Configuration file for running the geometry module

profile: orbit
# profile: individual_spectra

# use_python_geolocation: yes

scene_spec:
  sza: [70.0, 70.0, 70.0]
  saa: [0.0, 0.0, 0.0]
  vza: [30.0, 30.0, 30.0]
  vaa: [0.0, 0.0, 0.0]

# orbit propagation
orbit:
  epoch: 2022-08-12T12:00:00.3981
  sat_height: 500.0 # km
  eccentricity: 0.0
  arg_perigee: 0.0
  mean_anomaly: 0.0
  ltan: 13.823 # decimal hours
  mean_motion_dot: 0.0
  drag_coeff: 0.0
  propagation_duration: 1.67 # hours

sensor:
  integration_time: 0.04 # seconds
  start_time: 13.73 # minutes wrt orbit epoch
  end_time: 13.80 # minutes wrt orbit epoch
  pitch: 0.0
  roll: 0.0
  yaw: 0.0

io_files:
  ckd: ckd.nc
  dem: gebco_ocssw_v2020.nc
  geometry: geometry.nc
  navigation: navigation.nc
