atmosphere:
  n_layers: 30
  layer_thickness: 1000
  surface_pressure: 101300

afgl_gases: [co2, h2o, ch4]

scale_gas:                  #only relevant for AFGL profiles
    xco2: 410.              #ppm
    xch4: 1800.             #ppb
    xh2o: 10000.            #ppm

sentinel2:
    band_label: ['B02', 'B03', 'B11']   # use e.g. https://en.wikipedia.org/wiki/Sentinel-2 for band defintion
    date_range: [1900-01-01, 3000-01-01]

io_files:
    geometry: geometry.nc
    afgl: ../common/prof.AFGL.US.std
    atmosphere: sgm_atmosphere.nc
