#cal_level: raw  # to switch off ACD

swath:
  exact_drawing:  True

detector:
#  exposure_time: 0.0045    #FMC 1
#  exposure_time: 0.013     #FMC 2
#  exposure_time: 0.0215    #FNC 3
#  exposure_time: 0.030     #FMC 4
  exposure_time: 0.0385    #FMC 5
  binning_table_id: 5
  nr_coadditions: 3

isrf:
  # enabled: no
  fwhm_gauss: 0.45

dark:
  enabled: no

noise:
  enabled: yes
  seed: 10

prnu:
  enabled: no

stray:
  enabled: no

io_files:
  ckd: ../common/ckd.nc
  binning_table: ../common/binning_table.nc
  sgm: sgm_radiance.nc
  l1a: l1a.nc
  geometry: geometry.nc
