# Input for Tango L1B code

processing_version: 1.0

# cal_level: rad

dark:
  enabled: no

prnu:
  enabled: no

stray:
  van_cittert_steps: 0

swath:
  exact_drawing: False # default False

bin_spectra: 5

# geolocation:
#   enabled: no

io:
  ckd: ../common/ckd.nc
  binning_table: ../common/binning_table.nc
  l1b: l1b.nc
  l1a: l1a.nc
  geometry: geometry.nc
