# Input and output file configuration
io_files:
  input_sgm: sgm_atmosphere.nc
  input_sgm_ref: sgm_atmosphere_ref.nc # Path to the input reference file containing geographical and atmospheric data
  input_l2: l2.nc  # Path to the input reference file containing geographical and atmospheric data
  output_l4: l4.nc  # Path to the output file where the simulated Level 4 data will be saved

emission_estimation:
  method: ["microhh_fit"]
  species: ["XCO2 proxy"]
