sedf:               #parameter to configure the 2D blurring of the scene
  fwhm_x:   80                #FWHM in ACT direction
  fwhm_y:  300                #FWHM in flight direction

binning_act: 1                  #ACT binning of the convolved atm data for reference output.

spec_lbl_settings:              #settings for line-by-line spectra
    wave_start: 1575            #nm
    wave_end:   1685            #nm
    dwave:      0.002           #nm

xsec_forced: False              #flag to force new cross section calculation

atmosphere:
  n_layers: 30
  layer_thickness: 1000
  surface_pressure: 101300

isrf_settings:
  fwhm: 0.45

selected_gases: ['co2','ch4','h2o']

io_files:
  geometry: geometry.nc
  sun_reference: ../common/solar_spectrum.nc
  hapi: ../common/hapi/
  afgl: ../common/prof.AFGL.US.std
  atmosphere: sgm_atmosphere.nc
  atmosphere_ref: sgm_atmosphere_ref.nc
  radiance: sgm_radiance.nc
  dump_xsec: xsec.pkl
