sim_with_noise: True
     
spec_settings:                                     #settings for spectral grid of measurements
    wave_start: 1590.0009375                       #nm
    wave_end:   1675                               #nm
    dwave:      0.1546875                          #nm

#isrf_settings:
#    type:       'generalized_normal'               #type of ISRF, currently only Gaussian or generalized_normal
#    fwhm:       0.45                               #fwhm  [nm]
#    bcoeff:     0.45                               #only for generalized_normal, bcoeff=1/2 means Gaussian

isrf_settings:
    type:       'Gaussian'                         #type of ISRF, currently only Gaussian or generalized_normal
    fwhm:       0.45                               #fwhm  [nm]
    
snr_model:                                         #SNR instrument model a nd b coefficients
    a_snr:      1.54E-12                           #[e- m2 sr s nm/phot.]
    b_snr:      45501                              #[e-]
    seed:       5                                  #seed for measurement noise
    
io_files:
    input_sgm: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_radiance_exp1.0.nc'
    input_gm: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/gm/Tango_Carbon_gm_exp1.0.nc'
    output_l1b: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/level1b/Tango_Carbon_l1b_exp1.0.nc'
