#this file contains all paths of the end-to-end simulator
project = '/home/raul/Projects/tango/end_to_end/'

GM_module     = 'end_to_end/GM/'
SGM_module    = 'end_to_end/SGM/'
IM_module     = 'end_to_end/IM/'
L1AL1B_module = 'end_to_end/L1AL1B/'
L1L2_module   = 'end_to_end/L1L2/'
SIML1B_module = 'end_to_end/SIML1B/'
libaries      = 'end_to_end/lib/'

data_harpi    = '../data/hapi/'
data_afgl     = '../data/AFGL/'
data_microHH  = '../data/microHH/'
data_sol_spec = '../data/solar_spectra/'
data_harpi    = '../data/tmp/'
data_interface= '../data/interface_data/'
data_tmp      = '../data/tmp/'

interface_sgm = 'sgm/'
interface_l2  = 'level2/'
interface_l1b = 'level1b/'
interface_l1a = 'level1a/'
interface_gm  = 'gm/'
interface_ckd = 'ckd/'
