# =============================================================================
# 
#  Current version of the Tango E2E simulator can handle the following profiles
#   1.  individual_spectra: In this case only one single spectrum is processed. The IM 
#       and L1 processor cannot be used in this case but are replaced by the simplified moduel siml1.
#   2.  single_swath: This profile acounts for a single swath and a homogenous 
#       reference scene. It is meant to test the IM and the L1 processor
#   3.  S2_microHH: Same as S2_hom_atm but for microHH CO2 plume simulations    
# =============================================================================
profile: 'S2_microHH'  

run_id: 'run0001'

setup:
    flag_gm:     True
    flag_sgm:    True
    flag_im:     True
    flag_l0l1b:  True
    flag_siml1b: False
    flag_l1bl2:  False
    
individual_spectra:               #gm settings for reference scene, should be all lists
    sza: [70., 60, 50, 40, 30, 20, 10, 0]                #solar zenith angle[degree]
    saa: [0.,  0., 0., 0., 0., 0., 0., 0]                #solar azimuth angle [degree]
    vza: [0.,  0., 0., 0., 0., 0., 0., 0]                #viewing zenith angle [degree]
    vaa: [0.,  0., 0., 0., 0., 0., 0., 0]                #viewing azimuth angle [degree]        
    albedo: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]          #Lambertian surface alebdo of reference scene

single_swath:                     #gm settings for reference scene, should be all lists
    sza: 70.                      #solar zenith angle[degree]
    saa: 0.                       #solar azimuth angle [degree]
    vza: 0.                       #viewing zenith angle [degree]
    vaa: 0.                       #viewing azimuth angle [degree]        
    albedo: 0.15                  #Lambertian surface alebdo of reference scene
