# =============================================================================
#
#  Current version of the Tango E2E simulator can handle the following profiles
#   1.  individual_spectra: In this case only one single spectrum is processed. The IM
#       and L1 processor cannot be used in this case but are replaced by the simplified moduel siml1.
#   2.  single_swath: This profile acounts for a single swath and a homogenous
#       reference scene. It is meant to test the IM and the L1 processor
#   3.  S2_microHH: Same as S2_hom_atm but for microHH CO2 plume simulations
# =============================================================================
profile: 'single_swath'

run_id: 'run0001'

setup:
    flag_gm:     no
    flag_sgm:    yes
    flag_im:     no
    flag_l0l1b:  no
    flag_siml1b: no
    flag_l1bl2:  no


single_swath:
  sza: 70.0
  saa: 0.0
  vza: 0.0
  vaa: 0.0
  albedo: 0.15
