method : LSQ

simulationdata:
  sgm_atmosphere: "/data/manugv/git/end_to_end/data/sgm_atmosphere.nc"
  level2data:
    generate: True
    precision: 0.2 # give it in %
    # if generate is false then give a file input
    file: "/data/manugv/OwnCloud/TANGO/TANGO_E2ES/For_Manu/Tango_Carbon_l2_full_chain.nc"
  gas: "co2"
  lat_lon_src: [51.83472, 14.46277]

plumethreshold: 0.95
emission: 852.9  # kg/s

# if only method if CFM, then velocity data is needed from simulations
# only microHH simulations are supported as of now
CFM:
  microhh:
    path: "/data/manugv/OwnCloud/ToJochen/data_onefield/"
    time_stamp: 36000
  plumeheight: 300
