method : LSQ

simulationdata:
  sgm_atmosphere: "/data/manugv/OwnCloud/TANGO/TANGO_E2ES/For_Manu/Tango_Carbon_sgm_atmosphere_S2_microHH_exp0_run0001.nc"
  level2file: "/data/manugv/OwnCloud/TANGO/TANGO_E2ES/For_Manu/Tango_Carbon_l2_full_chain.nc"
  gas: "co2"
  lat_lon_src: [51.83472, 14.46277]

plumethreshold: 0.95
emission: 852.9  # kg/s

# if only method if CFM, then velocity data is needed from simulations
# only microHH simulations are supported as of now
CFM:
  microhh:
    path: "/data/manugv/OwnCloud/ToJochen/data_onefield/"
    time_stamp: 36000
  plumeheight: 300
