profile: orbit

atmosphere:
    nlay: 30                    #number of atmospheric layers
    dzlay: 1000                 #geometrical thickness of the layers [m]
        
afgl:                           #configure use of AFGL background
    afgl_only: False            #true means homogenous AFGL background only
    gases: ["co2", "h2o", "ch4", "o3", "no2"]

scale_gas:                  #only relevant for AFGL profiles 
    xco2: 410.              #ppm
    xch4: 1800.             #ppb
    xh2o: 10000.            #ppm

sentinel2:
    band_label: ['B02', 'B03', 'B11']   # use e.g. https://en.wikipedia.org/wiki/Sentinel-2 for band defintion

aerosol:
    add_aerosol: true       # Add aerosol information to geoscene
    echam_year: 2017        # Date for ECHAM data
    echam_month: 1
    echam_day: 15

surface:
    add_brdf: true                      # Add BRDF/BPDF data to geoscene
    use_surface_classification: false   # Set to true to use Sentinel-2 surface classification to assign albedo. If false, use coordinate-based LUT
    brdf_year: 2017
    brdf_month: 1
    brdf_day: 15

io_files:
    input_gm: '/Users/petersk/Tango_E2ES/data/interface_data2/gm/Tango_Carbon_gm_exp10.nc'
    input_afgl: '/Users/petersk/Tango_E2ES/data/AFGL/prof.AFGL.US.std'
    output_geo: '/Users/petersk/Tango_E2ES/data/interface_data2/sgm/Tango_Carbon_sgm_atmosphere_exp10.nc'
    aerosol:
        path_refr_index: '/Volumes/hammerspace/DATA_CLEAN/ORBIT_SOURCE_DATA/REFR_INDEX/'
        path_echam: '/Volumes/hammerspace/DATA_CLEAN/ORBIT_SOURCE_DATA/ECHAM/'
    surface:
        path_xbrdf: '/Volumes/hammerspace/DATA_CLEAN/ORBIT_SOURCE_DATA/SURFACE_DATA/'
        path_xbpdf: '/Volumes/hammerspace/DATA_CLEAN/ORBIT_SOURCE_DATA/POLDER_Aerosol_Data/'

Matimga:
    input_s2: '/Users/petersk/Tango_E2ES/data/Sentinel2/S2_Matimba.nc'
    meteo:                          #configure use of microHH plume simulation
        path_data: "/Users/petersk/Tango_E2ES/data//microHH/Matimba/"
        filesuffix: "src2_20200724_1100"  # sourcename_yyyymmdd_hhmm
        gases: ["co2", "no2", "no"]

Jaenschwalde:
    input_s2: '/Users/petersk/Tango_E2ES/data/Sentinel2/S2_Jaenschwalde.nc'
    meteo:                          #configure use of microHH plume simulation
        path_data: "/Users/petersk/Tango_E2ES/data/microHH/Jaenschwalde/"
        filesuffix: "src3_20180523_1100"  # sourcename_yyyymmdd_hhmm
        gases: ["co2", "no2", "no"]

Belchatow:
    input_s2: '/Users/petersk/Tango_E2ES/data/Sentinel2/S2_Belchatow.nc'
    meteo:                          #configure use of microHH plume simulation
        path_data: "/Users/petersk/Tango_E2ES/data/microHH/Belchatow/"
        filesuffix: "src3_20180606_1100"  # sourcename_yyyymmdd_hhmm
        gases: ["co2", "no2", "no"]

Lipetsk:
    input_s2: '/Users/petersk/Tango_E2ES/data/Sentinel2/S2_Lipetsk.nc'
    meteo:                          #configure use of microHH plume simulation
        path_data: "/Users/petersk/Tango_E2ES/data/microHH/Lipetsk/"
        filesuffix: "src2_20190613_1000" # sourcename_yyyymmdd_hhmm
        gases: ["co2", "no2", "no"]
