retrieval_init:                 #initialization parameter for inversion
    max_iter: 35
    chi2_lim: 0.05
    sw_pixel_mask: False
    sw_ALT_select: False
    first_ALT_index: 55
    last_ALT_index: 56
    sw_prof_init: 'sgm'         #switch between 'afgl' and 'sgm' initialization 
    
atmosphere:
    nlay: 30                    #number of atmospheric layers
    dzlay: 1000                 #geometrical thickness of the layers [m]
    psurf: 101300               #surface pressure [Pa]

std_atm: 'prof.AFGL.US.std'     #path to AFGL model atmosphere
        
spec_settings:              #spectra fit window
    wavestart:   1590       #initial wavelength (indicator)
    waveend:     1675       #final wavlength of measurement
    wave_extend: 2.0        #shortwave and longwave extension of the measurement grid [nm]
    dwave:       0.002      #nm

isrf_settings:
    type:       'generalized_normal'               #type of ISRF, currently only Gaussian or generalized_normal
    fwhm:       0.45                               #fwhm  [nm]
    bcoeff:     0.2                                #only for generalized_normal, bcoeff=1/2 means Gaussian
    
#isrf_settings:
#    type:       'Gaussian'                         #type of ISRF, currently only Gaussian or generalized_normal
#    fwhm:       0.45                               #fwhm  [nm]

surface:
    wave_alb: [1600, 1650]  #wavelengths at which the surface albedo is specified in the output
    
xsec_forced: False          #flag to froce new cross section calculation

