profile: 'orbit'


sedf:
    fwhm_x:   80                #FWHM in ACT direction
    fwhm_y:  300                #FWHM in flight direction

binning_act: 1                  #ACT binning of the convolved atm data for reference output.

spec_lbl_settings:              #settings for line-by-line spectra
    wave_start: 1575            #nm
    wave_end:   1685            #nm
    dwave:      0.002           #nm

xsec_forced: False              #flag to force new cross section calculation

atmosphere:
  n_layers: 30
  layer_thickness: 1000
  surface_pressure: 101300

spec_conv_settings:             #spectra fit window for spectral convolution in case convolve_input = False
    wavestart:   1587           #initial wavelength (indicator)
    waveend:     1678           #final wavlength of measurement
    dwave:       0.05           #nm

isrf_settings:
  fwhm:       0.45            #fwhm  [nm]
  shape: 2.0

afgl_gases: ['co2','ch4','h2o']

io_files:
  geometry: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/gm/Tango_Carbon_gm_exp7.0.nc'
  sun_reference: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/solar_spectra/hybrid_reference_spectrum_c2021-03-04_with_unc.nc'
  hapi: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/harpi/'
  afgl: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/AFGL/prof.AFGL.US.std'
  atmosphere: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_atmosphere_exp7.0.nc'
  radiance: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_radiance_exp7.0.nc'
  atmosphere_ref: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_atmosphere_ref_exp7.0.nc'
  dump_xsec: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/tmp/Tango_Carbon_xsec_exp7.0.pkl'
