retrieval_init:                 #initialization parameter for inversion
    max_iter: 35
    chi2_lim: 0.05

pixel_mask: False

atmosphere:
    nlay: 30                    #number of atmospheric layers
    dzlay: 1000                 #geometrical thickness of the layers [m]
    psurf: 101300               #surface pressure [Pa]

std_atm: 'prof.AFGL.US.std'     #path to AFGL model atmosphere
    
filename:
    level2:       'Tango_Carbon_l2'       #output file for geophysical scene
    level1b:      'Tango_Carbon_l1b'      #gm output file
    pixel_mask:   'level1b_pixel_mask'    #pixel mask
    
spec_settings:              #settings for line-by-line spectra
    wavestart:   1590       #initial wavelength (indicator)
    waveend:     1675       #final wavlength of measurement
    wave_extend: 2.0        #shortwave and longwave extension of the measurement grid [nm]
    dwave:       0.002      #nm

isrf_settings:
    type:       'generalized_normal'               #type of ISRF, currently only Gaussian or generalized_normal
    fwhm:       0.45                               #fwhm  [nm]
    bcoeff:     0.2                                #only for generalized_normal, bcoeff=1/2 means Gaussian
    
#isrf_settings:
#    type:       'Gaussian'                         #type of ISRF, currently only Gaussian or generalized_normal
#    fwhm:       0.45                               #fwhm  [nm]
#    bcoeff:     0.45                                #only for generalized_normal, bcoeff=1/2 means Gaussian

surface:
    wave_alb: [1600, 1650]  #wavelengths at which the surface albedo is specified in the output
    
xsec_forced: True          #flag to froce new cross section calculation

