# Cobined config file for all steps in E2E analysis.
#
header:
    file_name: 'full_config.yaml'
    version: '0.000'
#########################################################
# General settings. 
# Used by more than one step in the E2E simulator
#########################################################
gm_file: '../data/no2/geometry.nc'
sgm_rad_file: '../data/no2/sgm_radiance.nc'
sgm_atm_file: '../data/no2/sgm_atmosphere.nc'
#ckd_input: '../data/no2/ckd/ckd.nc'
#binning_table: '../data/no2/ckd/binning_table.nc'
#ckd_input: '../data/no2/ckd/ckd_nitro_20240229.nc'
ckd_input: '../data/no2/ckd/ckd_nitro_20240301.nc'
binning_table: '../data/no2/ckd/binning_table_no2.nc'
l1a_file: '../data/no2/l1a.nc'
l1b_file: '../data/no2/l1b.nc'
#########################################################
#
# GM 
# Configuration file for running the geometry module
#
#########################################################
#
profile: orbit
#        
orbit:
  epoch: 2022-08-12T12:00:00
  sat_height: 500.0     # km
  eccentricity: 0.0
  arg_perigee: 0.0
  mean_anomaly: 0.0
  ltan: 13.823            # decimal hours
  mean_motion_dot: 0.0
  drag_coeff: 0.0
  propagation_duration: 1.67 #hours
#
sensors:
  sensor_00__00:
    n_ground_pixels: 100
    swath_width: 30.0   # km
    integration_time: 0.04 # seconds
    end_time: 13.80   # minutes wrt orbit epoch
    end_time: 13.74   # minutes wrt orbit epoch
    pitch: 0.0
    roll: 0.0
    yaw: 0.0
# TODO: maybe we want to call this gm_output and gm_output_title?
# Following is common with L1AL1B. See below
#gm_file: '../data/no2/geometry.nc'
gm_title: 'Tango Nitro E2ES GM output'

#########################################################
#
# SGM nitro 
# Configuration file for running the SGM nitro module
#
#########################################################
kernel_parameter:               #parameter to configure the 2D blurring of the scene
    type:    2D Gaussian        #type pf kernel, current version has only one option
    fwhm_x:  300                #FWHM in ACT direction
    fwhm_y:  300                #FWHM in flight direction
    size_factor: 2              #the size of the convolution kernel in units of fwhm

atm: # atm simulation settings
    type: cams                  # cams or afgl atmosphere
    gases: [no2, o3]            # for now only no2 and o3
    afgl:
        nlay: 30                #number of atmospheric layers
        dzlay: 1000             #geometrical thickness of the layers [m]
        path: '../data/no2/prof.AFGL.US.std'
    cams:
        path: '../data/cams/cams_global_forecast_20230523.nc' # only contains 00:00 and 12:00 timeslices, 137 layers
        start: 2023-05-23T09:30:00  # different from GM date because it has to match microHH date
    microHH:
        use: True               # replace lower atm with microHH
        path_data: '../data/no2/microHH/Jaenschwalde_simulation1/'
        gases: [no2]
        filesuffix: src3_20180523_0930
        forced: no
        dump: '../data/no2/tmp/microHH_dump.pkl'
    dem:                       # correct surface pressure using tropomi dem (3k radius), only for CAMS
        use: True
        path: '../data/no2/dem.nc'

rtm:   # disamar (RTM) settings
    tmp_dir:    '../data/no2/tmp/'
    disamar_cfg_template: '../cfg/nitro/disamar_config_sim.in_template'
    disamar_exe: '/usr/people/leune/programs/disamar/Disamar_old.exe'
    dismas_sim: True
    dismas_fwhm: 0.05       #nm
    n_threads: 16
    wave_start: 405         #nm
    wave_end:   465         #nm
    dwave:      0.05        #nm
    cleanup: yes # rm disamar tmp directory when finished

S2_albedo:
    band: B01
    # B01: 442.7 nm (S2A), 442.3 nm (S2B) 60m
    # B02: 492.4 nm (S2A), 492.1 nm (S2B)    10m
    forced:   no     
    dump: '../data/no2/tmp/sgm_dumpfile.npy'

#########################################################
#
# IM specific
# Configuration file for running the Instrument module
#
#########################################################

rad_input: '../data/no2/sgm_radiance.nc'                              # TODO: remove, duplicate
IM_cfg_path:  '../cfg/nitro/'                                         #Where the .cfg file needed to run C++ code will be placed
IM_log_path:  '../logs/IM/'                                         #Where the .log file produced by the C++ code will be placed
# Following settings are common with L1AL1B
#ckd_input: '../data/no2/ckd/ckd.nc'
#binning_table: '../data/no2/ckd/binning_table.nc'
#l1a_file: '../data/no2/l1a.nc'
############################
settings_IM:
# Not used in create_im_config script:
#    fmc:             5                                  #forward motion compensation
    bin_id:          1                                   #across track binning
    co_adding:       2                                   #along track co-addng
    exp_time:        0.021                               #exposure time [sec]
#    co_adding:       4                                   #along track co-addng
#    exp_time:        0.066                               #exposure time [sec]
# Not used in create_im_config script:
#    stray_interpolating: yes                             #Whether to use interpolating stray light kernels
    sw_dark:         1                                   #switch dark current (1 on, 0 off)
    sw_nonlin:       0                                   #switch non-linearity (1 on, 0 off)
    sw_prnu:         1                                   #switch pixel response non-uniformity (1 on, 0 off)
    sw_stray:        0                                   #switch dark spectrometer stray light (1 on, 0 off)
    sw_rad:          1                                   #switch radiometric calibration (1 on, 0 off)
############################
isrf:
    convolution:     1                                   #switch spectral convolution (1=yes), (0=no)
    fwhm:            0.45                                #full width half max [nm]
############################    
select_images:       False                               #select certain images form the sgm input
first_image:         0
last_image:          1
############################
noise:
    switch:          0                                   # switch noise on (1) or off (0)
    seed:            100                                 #seed for random generator
############################    
#########################################################
#
# L1AL1B specific
# Configuration file for running the L1AL1B module 
#
#########################################################
#
# Following settings are common with IM
#ckd_input: '../data/no2/ckd/ckd.nc'
#binning_table: '../data/no2/ckd/binning_table.nc'
#l1a_file: '../data/no2/l1a.nc'
# Following is commom with GM
#gm_file: '../data/no2/geometry.nc'
#l1b_file: '../data/no2/l1b.nc'
#L1AL1B_path:  './'
L1AL1B_cfg_path:  '../cfg/nitro/'                                         #Where the .cfg file needed to run C++ code will be placed
L1AL1B_log_path:  '../logs/L1AL1B/'                                         #Where the .log file produced by the C++ code will be placed
############################
settings_L1AL1B:
    geolocation:  0       #calculate geolocation (0 no, 1 yes), currently only 0 possible
    van_cittert_steps: 4  #van Citter iteration for stray light correction (0=no correction)
    sw_dark:         1                                   #switch dark current (1 on, 0 off)
#   When non lin has been added to CKD sw_nonlin can be set to 1
    sw_nonlin:       0                                   #switch non-linearity (1 on, 0 off)
    sw_prnu:         1                                   #switch pixel response non-uniformity (1 on, 0 off)
#   When stray light has been added to CKD sw_stray can be set to 1
    sw_stray:        0                                   #switch dark spectrometer stray light (1 on, 0 off)
    sw_rad:          1                                   #switch radiometric calibration (1 on, 0 off)
############################    

