# Cobined config file for all steps in E2E analysis.
#
header:
    file_name: 'full_config.yaml'
    version: '0.000'
#########################################################
# General settings. 
# Used by more than one step in the E2E simulator
#########################################################
gm_file: '../data/no2/geometry.nc'
#
sgm_rad_file: '../data/no2/sgm_radiance.nc'
sgm_atm_file: '../data/no2/sgm_atmosphere.nc'
#ckd_input: '../data/no2/ckd/ckd.nc'
#binning_table: '../data/no2/ckd/binning_table.nc'
ckd_input: '../data/no2/ckd/ckd_nitro_20240301.nc'
binning_table: '../data/no2/ckd/binning_table_no2.nc'
#
l1a_file: '../data/no2/l1a.nc'
l1b_file: '../data/no2/l1b.nc'
l2_file: '../data/no2/l2.nc'

#########################################################
#
# GM 
# Configuration file for running the geometry module
#
#########################################################
#
profile: orbit
#        
orbit:
  epoch: 2022-08-12T12:00:00
  sat_height: 500.0     # km
  eccentricity: 0.0
  arg_perigee: 0.0
  mean_anomaly: 0.0
  ltan: 13.823            # decimal hours
  mean_motion_dot: 0.0
  drag_coeff: 0.0
  propagation_duration: 1.67 #hours
#
sensors:
  sensor_00__00:
    n_ground_pixels: 100
    swath_width: 30.0   # km
    integration_time: 0.04 # seconds
    start_time: 13.73 # minutes wrt orbit epoch
    end_time: 13.80   # minutes wrt orbit epoch
    pitch: 0.0
    roll: 0.0
    yaw: 0.0
gm_title: 'Tango Nitro E2ES GM output'

#########################################################
#
# SGM nitro 
# Configuration file for running the SGM nitro module
#
#########################################################
kernel_parameter:               #parameter to configure the 2D blurring of the scene
    type:    2D Gaussian        #type pf kernel, current version has only one option
    fwhm_x:  300                #FWHM in ACT direction
    fwhm_y:  300                #FWHM in flight direction
    size_factor: 2              #the size of the convolution kernel in units of fwhm

atm: # atm simulation settings
    type: cams                  # cams or afgl atmosphere
    gases: [no2, o3]            # for now only no2 and o3
    afgl:
        nlay: 30                #number of atmospheric layers
        dzlay: 1000             #geometrical thickness of the layers [m]
        path: '../data/no2/prof.AFGL.US.std'
    cams:
        path: '../data/cams/cams_global_forecast_20230523.nc' # only contains 00:00 and 12:00 timeslices, 137 layers
        start: 2023-05-23T09:30:00  # different from GM date because it has to match microHH date
    microHH:
        use: True               # replace lower atm with microHH
        path_data: '../data/no2/microHH/Jaenschwalde_simulation1/'
        gases: [no2]
        filesuffix: src3_20180523_0930
        forced: no
        dump: '../data/no2/tmp/microHH_dump.pkl'
    dem:                       # correct surface pressure using tropomi dem (3k radius), only for CAMS
        use: True
        path: '../data/no2/dem.nc'

rtm:   # disamar (RTM) settings
    tmp_dir:    '../data/no2/tmp/'
    disamar_cfg_template: '../cfg/nitro/disamar_config_sim.in_template'
    disamar_exe: '../data/no2/disamar/Disamar_old.exe'
    dismas_sim: True
    dismas_fwhm: 0.05       #nm
    n_threads: 16
    wave_start: 405         #nm
    wave_end:   465         #nm
    dwave:      0.05        #nm
    cleanup: yes # rm disamartmp directory when finished

S2_albedo:
    band: B01
    # B01: 442.7 nm (S2A), 442.3 nm (S2B) 60m
    # B02: 492.4 nm (S2A), 492.1 nm (S2B)    10m
    forced:   no     
    dump: '../data/no2/tmp/sgm_dumpfile.npy'

#########################################################
#
# IM specific
# Configuration file for running the Instrument module
#
#########################################################
IM_cfg_path:  '../cfg/nitro/'                                         #Where the .cfg file needed to run C++ code will be placed
IM_log_path:  '../logs/IM/'                                         #Where the .log file produced by the C++ code will be placed
# if output files of inbetween steps are needed define the steps for which output is required
# otherwise comment out l1x_output_files
l1x_output_files : 
    raw: '../data/no2/l1x_raw.nc'
    dark: '../data/no2/l1x_dark.nc'
    noise: '../data/no2/l1x_noise.nc'
    nonlin: '../data/no2/l1x_nonlin.nc'
    prnu: '../data/no2/l1x_prnu.nc'
    unbin: '../data/no2/l1x_unbin.nc'
    stray: '../data/no2/l1x_stray.nc'
    rebin: '../data/no2/l1x_rebin.nc'
    fov: '../data/no2/l1x_fov.nc'
    rad: '../data/no2/l1x_rad.nc'
############################
settings_IM:
# Not used in create_im_config script:
#    fmc:             5                                  #forward motion compensation## Not sure what this is for
    bin_id:          1                                   #across track binning
    co_adding:       2                                   #along track co-addng
    exp_time:        0.021                               #exposure time [sec]
# Not used in create_im_config script:
#    stray_interpolating: yes                             #Whether to use interpolating stray light kernels  ## Note sure what it is for
    sw_dark:         1                                   #switch dark current (1 on, 0 off)
    sw_nonlin:       0                                   #switch non-linearity (1 on, 0 off)
    sw_prnu:         1                                   #switch pixel response non-uniformity (1 on, 0 off)
    sw_stray:        0                                   #switch dark spectrometer stray light (1 on, 0 off)
    sw_rad:          1                                   #switch radiometric calibration (1 on, 0 off)
    sw_swath:        0                                   #switch swath stuff (1 on, 0 off)
    sw_noise:        0                                   #switch noise stuff (1 on, 0 off)
############################
isrf:
    convolution:     1                                   #switch spectral convolution (1=yes), (0=no)
    fwhm:            0.60                                #full width half max [nm] (for carbon: 0.45 and for nitro 0.60)
############################    
select_images:       False                               #select certain images form the sgm input
first_image:         0
last_image:          1
############################
noise:
    switch:          0                                   # switch noise on (1) or off (0)
    seed:            100                                 #seed for random generator
############################    
#########################################################
#
# L1AL1B specific
# Configuration file for running the L1AL1B module 
#
#########################################################
#
L1AL1B_cfg_path:  '../cfg/nitro/'                                         #Where the .cfg file needed to run C++ code will be placed
L1AL1B_log_path:  '../logs/L1AL1B/'                                       #Where the .log file produced by the C++ code will be placed
L1AL1B_instrument_cal:  'tango'                                           #Which instrument calibration is to be used (spexone or tango)
############################
settings_L1AL1B:
    geolocation:  0       #calculate geolocation (0 no, 1 yes), currently only 0 possible
    van_cittert_steps: 4  #van Citter iteration for stray light correction (0=no correction)
    sw_dark:         1                                   #switch dark current (1 on, 0 off)
#   When non lin has been added to CKD sw_nonlin can be set to 1
    sw_nonlin:       0                                   #switch non-linearity (1 on, 0 off)
    sw_prnu:         1                                   #switch pixel response non-uniformity (1 on, 0 off)
#   When stray light has been added to CKD sw_stray can be set to 1
    sw_stray:        0                                   #switch dark spectrometer stray light (1 on, 0 off)
    sw_rad:          1                                   #switch radiometric calibration (1 on, 0 off)
############################    
#########################################################
#
# L1L2 nitro 
# Configuration file for running the L1L2 nitro module
#
#########################################################
doas:
  threads: 6 # on KNMI workstation optimum around 6 threads

  rad_from_sgm: no
  irr_from_sgm: yes
  irr_file: ../data/no2/sgm_radiance.nc

  export_spectra: no
  debug:
    plot: no
    log: no

  # The window for the DOAS fit.
  fit_window: [405.0, 465.0] 

  #The number of coefficients of the DOAS polynomial (which is the degree of the polynomial + 1)# minimum is 3, maximum is 10.
  polynomial_coefs: 6

  #List of the trace gases to use, separated by spaces, e.g.: NO2  O3  O2O2  H2Ovap  H2Oliq
  # Do NOT include 'Ring' here!
  # Use 'None' for zero trace gases, i.e. fit only a polynomial.
  trace_gas_list: [NO2, O3]

  # Specify whether and if so how to fit the Ring spectrum:
  #    No  = do not apply Ring correction
  #    Iring = use the non-linear Ring correction approach,
  #            based on the Ring radiance spectrun Iring   
  #    sigma = use the linear Ring correction approach,    
  #            based on the differential Ring spectrum     
  ring_fit_term: No

  # Number of intensity offset correction coefficients:
  #    0 = no intensity offset correction
  #    1 = a constant   offset correction : Aoff
  #    2 = a linear     offset correction : Aoff + Boff*lambda
  # Note that fitting an intensity offset makes no sense if all
  # else there is to fit is a polynomial.
  # scaling factor Soff:  scaling factor to absorb the unit of IO(w)
  intensity_coefs: 0
  intensity_scaling_factor: 1.0

  # Maximum number of iterations to use in the DOAS fit
  max_iterations: 8

  # Spike removal: off/on
  spike_removal: off
  
  #Max number of outliers that iis accepted
  max_outliers: 10

  # convergence threshold for OE
  convergence_threshold: 1.0

  # ---- Reference Spectra ----
  # ref spec convolved with FWHM 0.6 nm
  ref_solar: ../data/no2/refspec_06/solar_irradiance.xs
  ref_xs_no2: ../data/no2/refspec_06/no2.xs
  ref_xs_o3: ../data/no2/refspec_06/o3.xs


  # ---- Wavelength calibration ----

  # Wavelength calibation for solar and earth spectra (off/on)
  wlcal_solar: off
  wlcal_earth: off

  # Include wavelength stretch in wavelength calibration(off/on)
  wlcal_solar_stretch: off
  wlcal_earth_stretch: off

  # window to use for the calibration, but use the full  
  #                   fit window if wlcal_[solar/earth]_stretch = 1
  wlcal_window: [405.0, 465.0]

  # prior values for OE: [value, error]
  prior:

    doas: # P is polynomial, C is intensity offset
      P0: [1.0, 1.0]
      P1: [0.015625, 0.015625]
      P2: [0.015625, 0.015625]
      P3: [0.015625, 0.015625]
      P4: [0.015625, 0.015625]
      P5: [0.015625, 0.015625]
      C0: [1.0, 1.0]
      C1: [0.125, 0.125]
      C2: [0.015625, 0.015625]
      C3: [0.015625, 0.015625]
      Cring: [0.06, 0.2]
      Dring: [0.06, 0.2]
      NO2: [1.2e-5, 1.0e-2]
      O2O2: [8.0e+5, 2.0e+6]
      O3: [3.6e-1, 5.0]
      H20vap: [1.5e+3, 1.0e+4]
      H20liq: [0.0, 20.0]
      
    wvl_cal: # ws = shift, wq = stretch/squeeze, error: 1/3th of spacing of nominal grid: sigma=dlambda/3
      ws: [0.0, 0.07]
      wq: [0.0, 0.07]
      P0: [1.0, 1.0]
      P1: [0.1, 0.1]
      P2: [0.01, 0.01]
      Cring: [0.06, 0.06]
      Dring: [0.06, 0.06]

amf:
    LUT_NN_file: ../data/no2/LUT_NN_combined_20231113.nc
