# All user configurable settings and their default values for the L1B
# processor

# Global attributes
instrument: Carbon
processing_version: ""

# Target calibration level
cal_level: L1B

# The first and last (inclusive) along-track positions to be include
# in processing.
image_start: 0
image_end: null

dark:
  # Whether to calibrate for dark offset and current
  enabled: yes

noise:
  # Whether to estimate noise
  enabled: yes

nonlin:
  # Whether to calibrate for pixel response nonlinearity
  enabled: yes

prnu:
  # Whether to calibrate for PRNU and quantum efficiency
  enabled: yes

stray:
  # Number of deconvolution iterations, 0 disables stray light calibration
  van_cittert_steps: 3

# Input/output file paths
io:
  # Calibration key data (CKD)
  ckd: ""
  # Binning table
  binning_table: ""
  # L1A or L1X product
  l1a: ""
  # Viewing and solar geometry
  geometry: ""
  l1b: ""
