profile: orbit

atmosphere:
  n_layers: 30
  layer_thickness: 1000
  surface_pressure: 101300

afgl_gases: ["co2", "h2o", "ch4"]

scale_gas:                  #only relevant for AFGL profiles
  xco2: 410.              #ppm
  xch4: 1800.             #ppb
  xh2o: 10000.            #ppm

sentinel2:
  band_label: ['B02', 'B03', 'B11']   # use e.g. https://en.wikipedia.org/wiki/Sentinel-2 for band defintion

io_files:
  geometry: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/gm/Tango_Carbon_gm_exp7.0.nc'
  afgl: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/AFGL/prof.AFGL.US.std'
  atmosphere: '/home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_atmosphere_exp7.0.nc'
