#cal_level: raw  # to switch off ACD

#image_start: 0
#image_end: 70

detector:
  binning_table_id: 1
  exposure_time: 0.0460833
  nr_coadditions: 3

isrf:
  # enabled: no
  fwhm_gauss: 0.45

# dark:
#   enabled: no

noise:
  enabled: yes
  seed: 10

# prnu:
#   enabled: no

# stray:
#   enabled: no

io:
  ckd: /home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/ckd/ckd_Raul_20241111.nc
  binning_table: /home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/ckd/binning_table.nc
  sgm: /home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/sgm/Tango_Carbon_sgm_radiance_exp1.0.nc
  l1a: /home/jochen/TANGO_E2ES/EndtoEndProject/data/interface_data/level1a/Tango_Carbon_l1a_exp1.0.nc