# Template for building Python packages

name: Python Package Builder

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string

jobs:
  container-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Container
        run: |
          cd ${{ inputs.project-path }}
          make container

      - name: Test Container
        run: |
          cd cd ${{ inputs.project-path }}
          make test-container

#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Push Container
#        run: docker push dockerhub-username/your-image-name:latest