# This workflow will build the Docker image for the `rad_offset_gain`
# example and upload the distributions as artifacts.

name: rad_offset_gain - Docker Image

on:
  workflow_dispatch:

  push:
    branches: [ "tomd/refactoring" ]
    paths:
      - "examples/exp3_rad_offset_gain/**"
      - ".github/workflows/rad_offset_gain**"

  pull_request:
    branches: [ "tomd/refactoring" ]
    paths:
      - "examples/exp3_rad_offset_gain/**"
      - ".github/workflows/rad_offset_gain**"

permissions:
  contents: read

jobs:
  call-builder:
    uses: ./.github/workflows/template_container-build.yml
    with:
      project-path: examples/exp3_rad_offset_gain
