# This workflow will build the Docker image for the `rad_offset_gain`
# example and upload the distributions as artifacts.

name: rad_offset_gain - Build Docker Image

on:
  workflow_dispatch:

  push:
    branches: [ "tomd/refactoring" ]
    paths:
      - "examples/exp3_rad_offset_gain/**"
      - ".github/workflows/rad_offset_gain**"

  pull_request:
    branches: [ "tomd/refactoring" ]
    paths:
      - "examples/exp3_rad_offset_gain/**"
      - ".github/workflows/rad_offset_gain**"

permissions:
  contents: read

jobs:
  release-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Container
        run: |
          cd examples/exp3_rad_offset_gain
          make container

#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Push Container
#        run: docker push dockerhub-username/your-image-name:latest
