# This workflow will build and upload a Python Package to PyPI

name: rad_offset_gain - Python Package

on:
  workflow_dispatch:
  push:
    branches: [ "tomd/refactoring" ]
    paths:
      - "examples/exp3_rad_offset_gain/**"
      - ".github/workflows/rad_offset_gain**"

  pull_request:
    branches: [ "tomd/refactoring" ]
    paths:
      - "examples/exp3_rad_offset_gain/**"
      - ".github/workflows/rad_offset_gain**"

  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  call-builder:
    uses: ./.github/workflows/template_python-package.yml
    with:
      project-path: examples/exp3_rad_offset_gain

